In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [5]:
nplist = np.array(mylist)

In [6]:
type(nplist)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5,2)

array([[0.78355688, 0.06229332],
       [0.59416811, 0.02242304],
       [0.63896233, 0.57750289],
       [0.63365854, 0.01750541],
       [0.54999702, 0.14019187]])

In [30]:
np.random.randint(1,10000, (4,5))

array([[5500, 4852, 1167, 3158,  376],
       [5250, 8551, 8277, 1041, 1556],
       [4163, 2533, 4349, 5394, 8435],
       [7105, 3062, 7630, 1235, 6268]])

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [39]:
arr = np.arange(0,30)

In [40]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 30 into shape (5,4)

In [42]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
nparr = np.random.randint(0,101, 10)

In [44]:
nparr

array([99, 23,  2, 21, 52,  1, 87, 29, 37,  1])

In [45]:
nparr.max()

99

In [46]:
nparr.min()

1

In [47]:
nparr.argmax()

0

In [49]:
nparr.argmin()

5

In [50]:
nparr.dtype

dtype('int64')

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
arr.shape

(30,)

In [54]:
arr = arr.reshape(6,5)

In [55]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [57]:
arr.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## lect #2

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:5:2]

array([0, 2, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100 ## broadcasting reassignment

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
slice_of_arr = arr[0:5]

In [15]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

2d arr

In [28]:
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr2d.shape

(3, 3)

In [31]:
arr2d[1]

array([20, 25, 30])

In [34]:
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [35]:
arr2d[:2, :]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [36]:
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr = np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
boolarr = arr>4

In [43]:
arr[boolarr]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## lect #3. Numpy Operations

In [45]:
import numpy as np

In [48]:
arr = np.arange(0,10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [53]:
arr.sum()

45

In [54]:
arr.max()

9

In [55]:
arr.std()

2.8722813232690143

In [56]:
arr2d = np.arange(0,25).reshape(5,5)

In [57]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr2d.sum(axis=0) # Y축

array([50, 55, 60, 65, 70])

In [61]:
arr2d.sum(axis=1) # X축

array([ 10,  35,  60,  85, 110])